parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
  babelOptions:
    presets:
      - "@babel/preset-react"
extends:
  - "airbnb"
  - "prettier"
plugins:
  - "prettier"
overrides:
  - files:
      - "**/*.test.js"
      - "**/*.test.jsx"
    plugins:
      - "jest"
    extends:
      - "plugin:jest/recommended"
    env:
      jest: true
env:
  browser: true
  node: true
