parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
  babelOptions:
    presets:
      - "@babel/preset-react"
extends:
  - "airbnb"
  - "prettier"
plugins:
  - "prettier"
env:
  browser: true
  node: true
