parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
  babelOptions:
    presets:
      - "@babel/preset-react"
extends:
  - "airbnb"
  - "prettier"
plugins:
  - "prettier"
overrides:
  - files:
      - "**/*.test.js"
      - "**/*.test.jsx"
    plugins:
      - "jest"
    extends:
      - "plugin:jest/recommended"
    env:
      jest: true
rules:
  jsx-a11y/label-has-associated-control:
    - 2
    - controlComponents:
        - "Input"
      labelComponents:
        - "Label"
env:
  browser: true
  node: true
