parser: "@babel/eslint-parser"
parserOptions:
  requireConfigFile: false
  babelOptions:
    presets:
      - "@babel/preset-react"
extends:
  - "airbnb"
  - "prettier"
  - "plugin:storybook/recommended"
plugins:
  - "prettier"
overrides:
  - files:
      - "**/*.test.js"
      - "**/*.test.jsx"
    plugins:
      - "jest"
    extends:
      - "plugin:jest/recommended"
    env:
      jest: true
  - files:
      - "**/stories.jsx"
    rules:
      react/jsx-props-no-spreading: 0
rules:
  react/jsx-props-no-spreading:
    - 2
    - html: "ignore"
env:
  browser: true
  node: true
